config/routes.rb
Rails.application.routes.draw do

 root 'home#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #resources :companies
  resources :companies do
  	resources :job_postings
  end
  resources :workers do 
  	resources :job_searches
  end


end

app/models/job_search.rb
class JobSearch < ApplicationRecord 
	belongs_to :worker
end	

app/controllers/job_searches_controller.rb
class JobSearchesController < ApplicationController
	before_action :load_worker_id
	load_and_authorize_resource :worker
	def index
		@job_searches = JobSearch.where(worker_id: params[:worker_id])
	end

	def new
		@worker = Worker.find(params[:worker_id])
		@job_search = JobSearch.new
	end

	def create
		@job_search = JobSearch.create(search_string: params[:job_search][:search_string], worker_id: worker_id_param, distance: distance_param)
		redirect_to worker_job_search_path(worker_id: worker_id_param, id: @job_search[:id])
	end

	def show 

		@job_search = JobSearch.find(params[:id])
		if(@job_search[:distance].present?)
			@distance = @job_search[:distance]
		else
			@distance = 50
		end
		@worker = Worker.find(worker_id_param)
		@companies = Company.near(@worker.preferred_address, @distance).join_jobs_nearby.job_posting_search("#{@job_search[:search_string]}")
	end

	private

	def search_string_param
		params.require(:job_search).permit(:search_string)
	end

	def worker_id_param
		params.require(:worker_id)
	end

	def distance_param
		params.require(:distance)
	end

	def load_worker_id
		@worker_id =  params[:worker_id]
	end


end

app/views/job_searches/index.html.erb
<div class="overall-spacing">
  <h1>Job Search History</h1> 
  <div>
  <%= link_to "Search Jobs", new_worker_job_search_path(params[:worker_id]) %>
  </div>



  <% if @job_searches.present? %> 
    <table id="job_searches" class="table">
    <thead>
      <tr>
      	<th>Id</th>
        <th>Search Term</th>
      </tr>
    </thead>
    <tbody>
      <% @job_searches.each do |job_search| %>
        <tr>
          <td><%= job_search[:id] %></td>
          <td><%= job_search[:search_string] %></td>
        </tr>
      <% end %>
    </tbody>
    </table>
  <% else %> 
  	No Searches 
  <% end %>

  <div>
  <%= link_to "Search Jobs", new_worker_job_search_path(params[:worker_id]) %>
  </div>

  <div>
  <%= link_to "Go Back", worker_path(params[:worker_id]) %>
  </div>
</div>

app/views/job_searches/new.html.erb
<div class="overall-spacing">
  <%= form_for  [@worker, @job_search] do |f| %>	
    <div class="form-group">
        <%= f.label :search %>
        <%= f.text_field :search_string, class: "form-control" %>
    </div>

    <div class="form-group"> 
    		<%= f.label :distance %>
    		<input type="text" id="distance-field" name="distance" class="form-control">
    </div>

     <div class="actions">
      <%= f.submit "Submit", class: "btn btn-primary" %>
      <%= hidden_field_tag 'worker_id', "#{@worker.id}" %>
    </div>
   
    <% if @worker.physical_addresses.present? %>
    	<h3>Your Address </h3>
    	<% address = @worker.physical_addresses.first %>
  	<div>
  		<%= address[:street] %>	 
  	</div>

  	<div>
  		<%= address[:city] %>	 
  	</div>

  	<div>
  		<%= address[:state] %>	 
  	</div>

  	<div>
  		<%= address[:zip] %>	 
  	</div>
    <% end %>
  <% end %>

  <%= link_to "Back", worker_job_searches_path(params[:worker_id]) %> 
</div>

app/views/job_searches/show.html.erb
<div class="map-spacing">
  <div> You searched for "<%= @job_search[:search_string] %>" within a <%= @distance %> radius</div>

  <br> </br>
  <% if @companies.present? %>
      <div class="job-search-map-container">  
        <div class="job-search-locations">
            <h1> Locations </h1>
            <% @companies.each do |company| %> 
                <div class="get-company-map-location">
                  Name: <%= company[:name] %> 
                  <input class="company-address" type="hidden" value="<%= company.address %>" name="addresses[]"> 
                </div>
                <div>Location: <%= company.address %> </div>

                <br><br>
            <% end %> 
        </div>

        </div class="job-search-map">
           <div id="map"></div>
        </div>

      </div>



      <script>
      var map;
  var geocoder; 
  var gmarkers = [];
  var infowindow; 
  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: -34.397, lng: 150.644},
      zoom: 8
    });

    infowindow = new google.maps.InfoWindow({
      content: ""
    });

    geocoder = new google.maps.Geocoder();
  }

  function geocodeAddress(geocoder, resultsMap, address, label_number) {
    geocoder.geocode({'address': address}, function(results, status) {
      if (status === 'OK') {
        resultsMap.setCenter(results[0].geometry.location);
        var marker = new google.maps.Marker({
          map: resultsMap,
          position: results[0].geometry.location,
          label: label_number,
        });
        marker.addListener('click', function() {
          infowindow = new google.maps.InfoWindow({
          content: "" + results[0].formatted_address + ""
          });
          infowindow.open(map, marker);
        });
        gmarkers.push(marker);
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }
  });
  }

  function removeMarkers(){
  for(i = 0; i< gmarkers.length; i++)
  {
    gmarkers[i].setMap(null);
  }
  }
        $("body").on("click", ".get-company-map-location", function(){
            var address = $(this).find(".company-address").val();
            geocodeAddress(geocoder, map, address, "" );
        });
        setTimeout(function(){ 
              <% if @companies.present? %>
                 <% @companies.each do |company| %>
                        geocodeAddress(geocoder, map,  "<%= company.address %>", "<%= company.name %>" );
                 <% end %> 
              <% end %>
        }, 2000);
      </script>
      <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['geolocation_key'] %>&callback=initMap"
      async defer></script>
  <% else %> 
    No Companies found in radius. Please search again. 
  <% end %> 

  <div class="move-buttons">
    <%= link_to "Search Jobs", new_worker_job_search_path(params[:worker_id]) %> 
     |
    <%= link_to "Job Search History", worker_job_searches_path(params[:worker_id]) %>
  </div>


</div>