config/routes.rb
Rails.application.routes.draw do

 root 'home#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #resources :companies
  resources :companies do
  	resources :job_postings
  end
  resources :workers do 
  	resources :job_searches
  end


end

app/models/job_posting.rb
class JobPosting < ApplicationRecord
	belongs_to :company, dependent: :destroy
	accepts_nested_attributes_for :company

	scope :worker_search, lambda {|search_string| where("lower(subject) LIKE lower(?)", "%#{search_string}%")}
	scope :company_join, lambda {joins("LEFT JOIN companies ON job_postings.company_id = companies.id")}
end		

app/controllers/companies/job_postings_controller.rb
class Companies::JobPostingsController < ApplicationController
	def index
		
	end
end

app/controllers/job_postings_controller.rb
class JobPostingsController < ApplicationController
	load_and_authorize_resource :company
	def index
		@job_postings = JobPosting.where(company_id: params[:company_id])
	end

	def new
		@company = Company.find(params[:company_id])
		@job_posting = JobPosting.new
		respond_to do |format|
	      format.html 
	      format.json { render json: @company }
	    end
	end

	def create
		@job_posting = JobPosting.new(subject: params[:job_posting][:subject], description: params[:job_posting][:description], company_id: params[:company_id] )
		if @job_posting.save
		  	redirect_to company_job_posting_path(company_id: params[:company_id], id: @job_posting[:id])
		else
			@company = Company.find(params[:company_id])
			@job_posting = JobPosting.new
			render :new
		end

	end	

	def show
		@job_posting = JobPosting.find(params[:id])
	end

	private

	def job_posting_params
		params.require(:job_posting).permit(:subject, :description, companies_attributes: [:id])
	end

end

app/views/job_postings/_form.html.erb
<%= form_for [@company, @job_posting] do |f| %>
	
  <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, class: "form-control" %>
  </div>

  <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control" %>
  </div>

 <div class="actions">
    <%= f.submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/job_postings/index.html.erb
<div style="margin-left:1em;">
    
<div>

<br>
<table id="job_postings" class="table">
<thead>
  <tr>
  	<th>Id</th>
    <th>Subject</th>
    <th>Description</th>
  </tr>
</thead>
<tbody>
  <% @job_postings.each do |job_posting| %>
    <tr>
      <td><%= job_posting[:id] %></td>
      <td><%= job_posting[:subject] %></td>
      <td><%= job_posting[:description] %></td>
    </tr>
  <% end %>
</tbody>
</table>


</div>




    <a href="<%= new_company_job_posting_path(params[:company_id]) %>">
	   New Job Posting
	 </a>

  <a href="<%= company_path(params[:company_id]) %>">
     Back
   </a>
</div>

<script>
$(document).ready(function() {
  $("#job_postings").dataTable();
});
</script>

app/views/job_postings/new.html.erb
<div class="overall-spacing"> 
	<div class="form-section">
	<h1> New Job Posting</h1>
		<div class="form-content">
				
			<%= render 'form' %>
	  	</div>

	  	<%= link_to "Back", company_job_postings_path(params[:company_id]) %>
	</div>
</div>

app/views/job_postings/show.html.erb
<div style="margin-left:1em;">
    <div> Subject: <%= @job_posting[:subject] %> </div>
    <div>Description: <%= @job_posting[:description] %></div>

    <%= link_to "Back", company_job_postings_path(params[:company_id]) %>
</div>